### Ordinal Encoding

In [15]:
import numpy as np
import pandas as pd

In [16]:
df = pd.read_csv('customer.csv')

In [17]:
df.sample(5)

age  gender   review education purchased
44   77  Female  Average        UG        No
49   25  Female     Good        UG        No
43   27    Male     Poor        PG        No
24   16  Female  Average        PG       Yes
26   53  Female     Poor        PG        No

In [18]:
df = df.iloc[: , 2:]


In [20]:
df.sample(5)

review education purchased
5   Average    School       Yes
12     Poor    School        No
20  Average    School       Yes
4   Average        UG        No
18     Good    School        No

In [23]:
from sklearn.model_selection import train_test_split

x_train  , x_test , y_train , y_test = train_test_split(df.iloc[: , 0:2] , df.iloc[ : , -1] , test_size=0.2)

### Ordinal Encoding
**1. it is used for INPUT columns**

In [36]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[['Poor','Average','Good'] , ['School','UG','PG']])

oe.fit(x_train)
x_train_enc = oe.transform(x_train)

In [37]:
x_train_enc

array([[0., 2.],
       [2., 1.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [2., 1.],
       [1., 2.],
       [1., 0.],
       [1., 1.],
       [2., 2.],
       [0., 2.],
       [1., 0.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [1., 1.],
       [0., 0.],
       [1., 0.],
       [0., 2.],
       [2., 2.],
       [2., 2.],
       [2., 0.],
       [0., 0.],
       [1., 2.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [2., 2.],
       [1., 1.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [1., 2.],
       [0., 1.]])

In [38]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [42]:
x_train_enc

array([[0., 2.],
       [2., 1.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [2., 1.],
       [1., 2.],
       [1., 0.],
       [1., 1.],
       [2., 2.],
       [0., 2.],
       [1., 0.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [1., 1.],
       [0., 0.],
       [1., 0.],
       [0., 2.],
       [2., 2.],
       [2., 2.],
       [2., 0.],
       [0., 0.],
       [1., 2.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [2., 2.],
       [1., 1.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [1., 2.],
       [0., 1.]])

### Perform LabelEncoder
**1. It is only use for OUTPUT columns**

In [44]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

le.fit(y_train)

y_train_enc = le.transform(y_train)



In [45]:
y_train_enc

array([0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0])